### ISSUE TITLE
dateFns.eachDayOfInterval is not a function Error on Version 4.0.0+

### ISSUE THREAD

**Issue by benjaminmesser** [grubersjoe/react-github-calendar#137]
For some reason I am getting the error `dateFns.eachDayOfInterval is not a function` whenever I try to use version 4.0.0 or later, but everything works fine on 3.4.0. It seems like this might be an issue with the `date-fns` library, as when I try using `require` with `date-fns` it gives me the same error. I've opened [an issue](https://github.com/date-fns/date-fns/issues/3950) over there, but I'm still curious why other people who are using this library aren't having the same issue as me. I figure it's just worth asking here as well to see if anyone might have some idea as to what might be causing this issue.

**Comment by grubersjoe** [comment]
Hey. Can you provide some example code or reproduction repo that demonstrates what you are trying to do? The following code runs for me with `date-fns` in version 3 _and_ 4 using Node 22:

```js
const dateFns = require('date-fns');
const d1 = new Date("2000-01-17T16:45:30");
const d2 = new Date("2000-02-17T16:45:30");
const days = dateFns.eachDayOfInterval({start: d1, end: d2});
console.log(days);
```

```js
node index.js

[
  2000-01-16T23:00:00.000Z, 2000-01-17T23:00:00.000Z,
  2000-01-18T23:00:00.000Z, 2000-01-19T23:00:00.000Z,
  2000-01-20T23:00:00.000Z, 2000-01-21T23:00:00.000Z,
  2000-01-22T23:00:00.000Z, 2000-01-23T23:00:00.000Z,
  2000-01-24T23:00:00.000Z, 2000-01-25T23:00:00.000Z,
  2000-01-26T23:00:00.000Z, 2000-01-27T23:00:00.000Z,
  2000-01-28T23:00:00.000Z, 2000-01-29T23:00:00.000Z,
  2000-01-30T23:00:00.000Z, 2000-01-31T23:00:00.000Z,
  2000-02-01T23:00:00.000Z, 2000-02-02T23:00:00.000Z,
  2000-02-03T23:00:00.000Z, 2000-02-04T23:00:00.000Z,
  2000-02-05T23:00:00.000Z, 2000-02-06T23:00:00.000Z,
  2000-02-07T23:00:00.000Z, 2000-02-08T23:00:00.000Z,
  2000-02-09T23:00:00.000Z, 2000-02-10T23:00:00.000Z,
  2000-02-11T23:00:00.000Z, 2000-02-12T23:00:00.000Z,
  2000-02-13T23:00:00.000Z, 2000-02-14T23:00:00.000Z,
  2000-02-15T23:00:00.000Z, 2000-02-16T23:00:00.000Z
]
```

**Comment by benjaminmesser** [comment]
Interesting. I am just running it in a simple React app. I'm not using a bundler so I'm really not sure. When I run that same code I get this:
![image](https://github.com/user-attachments/assets/8eb717da-183f-4d37-9dd6-391ea79d9323)

**Comment by grubersjoe** [comment]
Are you using Create React App? Or how was this React app created? If you this will not work, because CRA is unable to handle ESM which `date-fns` is using primarily now.

https://github.com/grubersjoe/react-github-calendar?tab=readme-ov-file#why-is-create-react-app-unsupported

**Comment by benjaminmesser** [comment]
> Are you using Create React App? Or how was this React app created? In this case it will not work, because CRA is unable to handle ESM which `date-fns` is using primarily now. Or more specifally unable to handle `.cjs` files that `date-fns` provides with v4. [See this comment](https://github.com/grubersjoe/react-activity-calendar/issues/105#issuecomment-2278822256).
> 
> This is also explained in the README: https://github.com/grubersjoe/react-github-calendar?tab=readme-ov-file#why-is-create-react-app-unsupported

You were right! I was using CRA. I didn't realize it was no longer supported. I switched from CRA to Vite and all of my issues went away. Thank you for the help on this!

**Comment by grubersjoe** [comment]
Perfect. Yes Vite really is the better choice nowadays in my opinion 👍.
